modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/BaderTim/minecraft-measurement-mod/issues"

[[mods]] 
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    #updateJSONURL="https://github.com/BaderTim/minecraft-measurement-mod/issues"
    displayURL="https://minecraft-measurement-mod.github.io"
    logoFile="mmm_logo.png"
    #credits="" 
    authors="${mod_authors}"
    displayTest="IGNORE_SERVER_VERSION" 
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge" 
    mandatory=true 
    versionRange="${forge_version_range}"
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
