modLoader="javafml"
loaderVersion="[46,)"
license="GNU General Public License v3.0 only"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" 

[[mods]] 
    modId="mmm" 
    version="1.0.0"
    displayName="Minecraft Measurement Mod" 
    #updateJSONURL="https://change.me.example.invalid/updates.json" 
    displayURL="https://minecraft-measurement-mod.github.io" 
    logoFile="mmm_logo.png"
    #credits="" 
    authors="Tim Bader" 
    displayTest="IGNORE_SERVER_VERSION" 
    description='''The Minecraft Measurement Mod allows the terrain to be measured from the player's perspective. Various measuring devices, such as LiDAR sensors, can be simulated. The measurement data can be saved externally.'''

[[dependencies.mmm]] 
    modId="forge" 
    mandatory=true 
    versionRange="[46,)" 
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"

[[dependencies.mmm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
